### ISSUE TITLE
Incorrectly detects unbounded with SOS1 constraint with non-binary variable

### ISSUE THREAD

**Issue by blegat** [coin-or/Cbc#363]
In the following problem:
max x
s.t. [x, y] in SOS1
y == 1 which is encoded in Cbc with:
```
Cbc_Model *model = Cbc_newModel();

CoinBigIndex start[] = {0, 0, 0};
int rowindex[] = {};
double value[] = {};
double collb[] = {-INFINITY,1.0};
double colub[] = {INFINITY,1.0};
double obj[] = {1.0,0.0};
double rowlb[] = {};
double rowub[] = {};

int sosrowstart[] = {0,2};
int soscolindex[] = {0,1};
double sosobj[] = {2.0,1.0};

Cbc_loadProblem(model, 2, 0, start, rowindex, value, collb, colub, obj, rowlb, rowub);
Cbc_addSOS(model, 1, sosrowstart, soscolindex, sosobj, 1);
```
Cbc outputs
```
Problem is unbounded - 0.00 seconds
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00
```
While the problem is expected to be bounded with optimal solution (0, 1). Indeed, as y is nonzero, the SOS1 constraint forces x to be zero.
I have noticed similar issues with larger problems. The problem seem to occur whenever the variables of the SOS1 constraint are not all binary.

**Comment by jjhforrest** [comment]
Benoit,

I think I have fixed problem.  I can put in master - what version of Cbc 
are you using?

John Forrest

**Comment by blegat** [comment]
> I think I have fixed problem

Glad to read that !

> what version of Cbc are you using?

I'm using the [Julia wrapper](https://github.com/jump-dev/Cbc.jl) which is using Cbc v2.10.3. Do you think updating to v2.10.5 would fix it ?

**Comment by jjhforrest** [comment]
Benoît,

v2.10.5 would have same problem.  I will update CbcSOS.cpp in master and 
send a version of CbcSOS.cpp (suitable for v2.10) just to you.  Tell me 
if you get problems on larger models.

When I tried to reproduce the error using an mps file and standalone cbc 
executable - the error did not occur.

John Forrest

**Comment by svigerske** [comment]
https://github.com/coin-or/Cbc/pull/725 puts a change as suggested in https://github.com/coin-or/Cbc/issues/376#issuecomment-803666887 into stable/2.10. This is for issue #376, which seems to be related to the one here. Or is it the same? Please check whether things are better with current stable/2.10.

Or if the CbcSOS.cpp that @jjhforrest sent to you in 2021 by e-mail worked, then is this something that can be integrated into stable/2.10? Maybe as a PR? Or has that happened and #725 was superfluous?

**Comment by odow** [comment]
I've updated Cbc.jl to v2.10.13 in https://github.com/jump-dev/Cbc.jl/pull/243 and this is still a problem:
```Julia
(jmp) pkg> st
Status `/private/tmp/jmp/Project.toml`
  [9961bab8] Cbc v1.3.0 `~/git/jump-dev/Cbc`
  [4076af6c] JuMP v1.31.2

(jmp) pkg> st -m Cbc_jll
Status `/private/tmp/jmp/Manifest.toml`
  [38041ee0] Cbc_jll v200.1000.1300+0

julia> using Cbc, JuMP

julia> function main_jump()
           model = Model(Cbc.Optimizer)
           @variable(model, x)
           @variable(model, y == 1)
           @constraint(model, [x, y] in SOS1())
           @objective(model, Min, x)
           optimize!(model)
           return solution_summary(model)
       end
main_jump (generic function with 1 method)

julia> main_jump()
Cbc3007W No integer variables - nothing to do
Welcome to the CBC MILP Solver 
Version: 2.10.13 
Build Date: Sep  1 2026 

command line - Cbc_C_Interface -solve -quit (default strategy 1)
Problem is unbounded - 0.00 seconds
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

solution_summary(; result = 1, verbose = false)
├ solver_name          : COIN Branch-and-Cut (Cbc)
├ Termination
│ ├ termination_status : INFEASIBLE_OR_UNBOUNDED
│ ├ result_count       : 1
│ ├ raw_status         : Cbc_status          = finished - check isProvenOptimal or isProvenInfeasible to see if solution found (or check value of best solution)
Cbc_secondaryStatus = linear relaxation unbounded

│ └ objective_bound    : 0.00000e+00
├ Solution (result = 1)
│ ├ primal_status        : FEASIBLE_POINT
│ ├ dual_status          : NO_SOLUTION
│ ├ objective_value      : 0.00000e+00
│ └ relative_gap         : Inf
└ Work counters
  ├ solve_time (sec)   : 2.31981e-04
  └ node_count         : 0
```

**Comment by jjhforrest** [comment]
Tried again - changed in stable.  The problem is that before entering the Cbc part of Coin the LP is solved - which does not know about the SOS - so it says unbounded.  If infeasible or unbounded it will not try Cbc.  Obviously this is correct for infeasible - but not for unbounded with SOS.  For the moment I just modify bounds for continuous variables in SOS.
